# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4341df40d4bd51f476308dfff12cbfe7987bb4964d6ec7e471b5c1269f00d87d426d97d98cb410ad9352e1c518bf5c6d39b5fda217865563a3a522b1401cb673

test:
  secret_key_base: c17a0018929b30e0348c458f50ec513be9cc0037020ea5fa9f8db3a791dee80296a724cf2517105ab71d7b134814d467cf101f70181d4a89d14fa44e66f4a51c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
